# Generated by Django 3.2.8 on 2022-08-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_social_linkedin'),
        ('project', '0007_review_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created']},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
