# Generated by Django 3.2.8 on 2022-08-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20220825_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_count', 'title']},
        ),
    ]
